project:
  type: website

website:
  title: "GEO511_FinalProject_Gursoy"
  navbar:
    left:
      - href: index.qmd
        text: HOMEPAGE
      - about.qmd

format:
  html:
    theme: cosmo
    includes:
        after_body: include/after_body.html
